def countNucleotides(string):
    a, c, g, t= 0, 0, 0, 0
    for nuc in string:
        if nuc == "A":
            a += 1
        elif nuc == "C":
            c += 1
        elif nuc == "G":
            g += 1
        elif nuc == "T":
            t += 1

    print(a,c,g,t)

countNucleotides("AGCATATTGACACTTAAATAGAAGACAAGCTCCGTCGCCAAACGTTGTGTACAAGAGACCCCCACAGTCGGGGTGAGGTTCCCGATTATCAGGGAGGTTAGGGACTGCAGCTATCCGGTTAGCCCTCCCTGATAATTCAGTCCGGAGTCCTGACACCGAAGACCCGTTAGGCCCGGAGCACTTAGGGGCTACGAAGAGGAGCTCTGTAAGGTCCTATTTTCCACGCAATAGCCTCCGGTTCAGTGAACTTATTAAACACTTAACTCGGATACAAGCTGAGAGCTTCCAGCTCTTATCTACCTGAACGAGGAGGTGCGCGCAACTTGTGGTGAACGTGCCGGGGCTCTGCGTACATATCCATGCTACGGCCGGCCGTGGAGAGGACTAGACGGCCAGTCACTGGAATTCGGGGACGGCTTTACTGCGCGCGGCAACGTTAGTACGCTTTCACTGTTTCAAGGCAGAGGTGATATGGGCGCTTAGTCCACTACACGCGCAGGAGTTCTATTAATCTACGTCGCACGCTAGCTTTGACAAGCGCCGCGTATCCGAATAGTAGCGCAGTTAAAGCGACTTCAACGCGCGCTCTCAGCTCTATCGTCAACGAGGTCTTATGGGATAGGGCTGTCTTCGGGACCCCGCGAGTCATCATACAAGTACACAACATCTAGAGGTTTGAAAGCCGCCTCGGGTCATGGTCTAAGGCATGGCTGTCTGACCTGATAGCAGGATCTATGGGATATTGCGAGGACAACTATTTCAAAGAATTGCCGGGCTATCTCTCTTCTGCAGCTCTTTGAGATTTTAGTTATAGTCCGCAGGCACAAGGCTGGCCACTGCTCGGCGCGGTCTATGACTTTCCGTAACGCGGTAGCTTAAC")
