def complement(dna):
    cdna = dna[::-1]
    cdna2 = []
    for x in cdna:
        if x == "A":
            cdna2.append("T")
        if x == "T":
            cdna2.append("A")
        if x == "G":
            cdna2.append("C")
        if x == "C":
            cdna2.append("G")
    print(*cdna2,sep="")

complement("TTGCCGCACGAAGCCGGAGCCCTTCGTCACATAAGGAACGCCAGCGTTTCGAATGACGTCTATGGCTGTGCGGGATGCAGTCCATTTAGCACTTCGGAATGCTGGTACCTCGAAGGTAACGCGCTTTGAACACTCTCTGACGCAAAACCTATAAGTCGGACCCGTGACGTGACATCAGCGTCAGTTTTCATACCAGCGGTCCTAAGAGACCGTTCAGGTTCTTCTCGGCGTGAGGTGGGTTTTGAACGGTGTTCGTCACGAAATGACCCTGGAGTGATACATTGTCGATGGGGCTGACATTGGGAAAATCCCTTTTTCGTCCGGGAGTTTTACGTACGACAGACGAACGATCATGGGACATAGATTTGCACTATCTGTTAGGGCAAATAAAAAGTAGTCTGCCGCATACCTGTCGAAGACTTCGTTATGCCAAAAAACTTTAGCGGTACGAATCAGAAATAAACACCCTATCTTAGCAAATATGTGTAATGGTTTGCTCGTATCAGGCCCCAGAGGCAATTTTGCGCAAATATGTGAGGCATCATGACCTTAATTCCCCAGATCACACGACTCTCAATACAGATTATGATGCTTGAAAGTCCCGAGGGGACCCCTAGTGTCGACTCATGAATCGCGTACCATTCTATATCCATAAATGCTACATTCGGGACCATTCCACAGAAGTATCATCCAACTCTGGGATTCGCCGGATGCCTCATATCAGCGATTACCCAAATGGGTTGTCCACCTGACAGCAAAGATACCTCACGTGGGGGACATAGCGTACGGACTGGAGTCTACGGGAAACCTAGGTTGGAGCCGATATCCGTCCGTCTCCGATAAGCGTGCAGCTAAATATAAAGAAACGGGGGAAACGGTAACTATTCCCGGTCACTCTCGGGGTTGGGAAGTATTGCGGGTACCCAACATATTTGTTACTACGTTGGTGAATCTGCGTCTACATGG")
